Controllers/GuestController.cs
using Microsoft.AspNetCore.Mvc;
using la_mia_pizzeria_static.Models;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers
{
    public class GuestController : Controller
    {
        private PizzaContext _db;

        public GuestController()
        {
            _db = new PizzaContext();
        }

        [HttpGet]
        public IActionResult Index()
        {
           
            return View(/*"Index", _db.pizzasList.Include(p => p.Category).Include("Ingredients").ToList()*/);
           
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Show(int id)
        {
            //try
            //{
            //    Pizza toShow = _db.pizzasList.Where(x => x.Id == id).Include(pizza => pizza.Category).Include("Ingredients").FirstOrDefault();
            //    return View("Show", toShow);
            //}
            //catch
            //{
            //    return View("Error");
            //}

            return View( id );
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    [Authorize]
    public class PizzaController : Controller
    {

        private readonly ILogger<PizzaController> _logger;

        public PizzaController(ILogger<PizzaController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {

            using (PizzaContext context = new PizzaContext())
            {
                //List<Pizza> pizzas = context.pizzasList.ToList<Pizza>();
                return View(/*"Index", context.pizzasList.Include(p => p.Category).Include("Ingredients").ToList()*/);
            }

        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            using (PizzaContext context = new PizzaContext())
            {
                List<Category> categories = context.categories.ToList();
                List<Ingredient> ingredients = context.Ingredients.ToList();
                PizzaCategory model = new PizzaCategory();
                model.Categories = categories;
                model.Ingredients = ingredients;
                model.Pizza = new Pizza();
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaCategory pizzaData)
        {
            if (!ModelState.IsValid)
            {
                pizzaData.Categories = new PizzaContext().categories.ToList();
                pizzaData.Ingredients = new PizzaContext().Ingredients.ToList();
                return View("Create", pizzaData);
            }

            using (PizzaContext context = new PizzaContext())
            {
                //Pizza pizza = new Pizza();
                //pizza.Name = formData.Name;
                //pizza.Description = formData.Description;
                //pizza.Photo = formData.Photo;
                //pizza.Price = formData.Price;

                pizzaData.Pizza.Ingredients = context.Ingredients.Where(ingredient => pizzaData.selectedIngredients.Contains(ingredient.Id)).ToList();

                context.pizzasList.Add(pizzaData.Pizza);

                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult EditForm(int Id)
        {
            //PizzaContext context = new PizzaContext();
            using (PizzaContext context = new PizzaContext())
            {
                try
                {
                    Pizza PizzaToEdit = context.pizzasList.Where(x => x.Id == Id).Include("Ingredients").First();

                    if (PizzaToEdit == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        PizzaCategory pizzaCategory = new PizzaCategory();
                        pizzaCategory.Pizza = PizzaToEdit;
                        pizzaCategory.Categories = context.categories.ToList();
                        pizzaCategory.Ingredients = context.Ingredients.ToList();
                        return View(pizzaCategory);
                    }
                }
                catch
                {
                    return View("Error");
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int Id, PizzaCategory dataForms)
        {
            using (PizzaContext context = new PizzaContext())
            {
                if (!ModelState.IsValid)
                {
                    dataForms.Categories = context.categories.ToList();
                    dataForms.Ingredients = context.Ingredients.ToList();
                    return View("EditForm", dataForms);
                }

                Pizza pizza = context.pizzasList.Where(pizza => pizza.Id == Id).Include("Ingredients").FirstOrDefault();

                pizza.Name = dataForms.Pizza.Name;
                pizza.Description = dataForms.Pizza.Description;
                pizza.Photo = dataForms.Pizza.Photo;
                pizza.Price = dataForms.Pizza.Price;
                pizza.CategoryId = dataForms.Pizza.CategoryId;
                pizza.Ingredients = context.Ingredients.Where(ingredient => dataForms.selectedIngredients.Contains(ingredient.Id)).ToList<Ingredient>();
                

                context.SaveChanges();

                return RedirectToAction("Index");

            }
            
        }

        public IActionResult Show(int id)
        {

            //using (PizzaContext db = new PizzaContext())
            //{

            //    try
            //    {
            //        Pizza toShow = db.pizzasList.Where(x => x.Id == id).Include(pizza => pizza.Category).Include("Ingredients").FirstOrDefault();
            //        return View("Show", toShow);
            //    }
            //    catch
            //    {
            //        return View("Error");
            //    }

            //}

            return View(id);

        }

        public IActionResult Delete(int Id)
        {
            PizzaContext context = new PizzaContext();
            Pizza toDelete = context.pizzasList.Where(x => x.Id == Id).First();

            if (toDelete != null)
            {
                context.pizzasList.Remove(toDelete);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }

}

Views/Shared/_GuestHeaderLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Pizzeria </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Guest" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Pizzeria </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.20.0/axios.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Pizza" asp-action="Index">Pizzeria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"> <a class="nav-link text-dark" aria-current="page" href="@Url.Action("Index", "Pizza")">Admin</a> </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Pizza" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>